name: vibration
description: A new flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gaetanschwartz.vibration
        pluginClass: VibrationPlugin
      ios:
        pluginClass: SwiftVibrationPlugin
